workflows:
  android-workflow:
    name: Android App CI/CD
    instance_type: linux_x2
    max_build_duration: 60
    working_directory: android
    environment:
      groups: []
        # - firebase_credentials  # Uncomment when Firebase Test Lab is configured
      vars:
        PACKAGE_NAME: "com.example.app"
        GOOGLE_PLAY_TRACK: alpha
        CM_BUILD_DIR: ".."
      java: 17
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*'
          include: true
          
    scripts:
      - name: Check project structure
        script: |
          pwd
          ls -la
          
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
          
      - name: Build Android App Bundle
        script: |
          ./gradlew bundleDebug
          
      - name: Run unit tests
        script: |
          ./gradlew test
          
      - name: Build debug and test APKs for Firebase Test Lab
        script: |
          ./gradlew assembleDebug
          ./gradlew assembleAndroidTest
          
      # Firebase Test Lab tests (uncomment when credentials are configured)
      # - name: Run Firebase Test Lab tests
      #   script: |
      #     echo $GCLOUD_KEY_FILE > $CM_BUILD_DIR/gcloud_key_file.json
      #     gcloud auth activate-service-account --key-file=$CM_BUILD_DIR/gcloud_key_file.json
      #     gcloud --quiet config set project $FIREBASE_PROJECT
      #     
      #     cd android
      #     
      #     # Run instrumentation tests on multiple devices
      #     gcloud firebase test android run \
      #       --type instrumentation \
      #       --app app/build/outputs/apk/debug/app-debug.apk \
      #       --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
      #       --device model=Pixel2,version=28,locale=en_US,orientation=portrait \
      #       --device model=Pixel4,version=30,locale=en_US,orientation=portrait \
      #       --device model=Nexus9,version=25,locale=en_US,orientation=landscape \
      #       --timeout 20m \
      #       --results-bucket gs://$FIREBASE_PROJECT-test-results \
      #       --results-dir $CM_BUILD_ID \
      #       || echo "Some tests failed, but continuing build"
      #       
      # - name: Run Robo tests for smoke testing
      #   script: |
      #     cd android
      #     
      #     # Quick automated exploration test
      #     gcloud firebase test android run \
      #       --type robo \
      #       --app app/build/outputs/apk/debug/app-debug.apk \
      #       --device model=Pixel4,version=30,locale=en_US,orientation=portrait \
      #       --timeout 10m \
      #       --robo-directives click:button_login=,text:username_field=testuser
            
      - name: Copy APK for download
        script: |
          cp app/build/outputs/apk/debug/app-debug.apk ../public/app-debug.apk || echo "Debug APK not found"
        
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/reports/tests/**/*
      - ../public/app-debug.apk
      
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
          
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true