name: Build Initial Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/notifications
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Create temporary keystore
      run: |
        cd android
        keytool -genkey -v -keystore temp-release.keystore -alias temp -keyalg RSA -keysize 2048 -validity 1 -storepass temp123 -keypass temp123 -dname "CN=Temp, OU=Temp, O=Temp, L=Temp, ST=Temp, C=US"
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build Release APK and AAB
      run: |
        cd android
        # Update build.gradle temporarily
        sed -i 's/linknode-release.keystore/temp-release.keystore/g' app/build.gradle
        sed -i 's/linknode2024/temp123/g' app/build.gradle
        sed -i 's/linknode/temp/g' app/build.gradle
        
        # Build both APK and AAB
        ./gradlew assembleRelease bundleRelease --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab