name: Build Internal Testing (Simple)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build output type'
        required: true
        default: 'aab'
        type: choice
        options:
          - apk
          - aab
          - both

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create temporary keystore
      run: |
        cd android
        keytool -genkey -v -keystore temp-release.keystore \
          -alias temp -keyalg RSA -keysize 2048 -validity 30 \
          -storepass temp123 -keypass temp123 \
          -dname "CN=Temp Testing, OU=Testing, O=Linknode Demo, L=SF, ST=CA, C=US" \
          -noprompt
        
    - name: Update build config for temp keystore
      run: |
        cd android/app
        # Create a temporary build.gradle with temp keystore
        sed -i 's|../linknode-release.keystore|../temp-release.keystore|g' build.gradle
        sed -i 's|"linknode2024"|"temp123"|g' build.gradle
        sed -i 's|"linknode"|"temp"|g' build.gradle
        # Show the changes for debugging
        echo "=== Updated signing config ==="
        grep -A5 "signingConfigs" build.gradle
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build Release APK
      if: ${{ github.event.inputs.build_type == 'apk' || github.event.inputs.build_type == 'both' }}
      env:
        KEYSTORE_PASSWORD: temp123
        KEY_ALIAS: temp
        KEY_PASSWORD: temp123
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon
        
    - name: Build Release AAB
      if: ${{ github.event.inputs.build_type == 'aab' || github.event.inputs.build_type == 'both' }}
      env:
        KEYSTORE_PASSWORD: temp123
        KEY_ALIAS: temp
        KEY_PASSWORD: temp123
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: |
        cd android
        ./gradlew bundleRelease --no-daemon
        
    - name: Upload APK
      if: ${{ github.event.inputs.build_type == 'apk' || github.event.inputs.build_type == 'both' }}
      uses: actions/upload-artifact@v4
      with:
        name: linknode-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Upload AAB
      if: ${{ github.event.inputs.build_type == 'aab' || github.event.inputs.build_type == 'both' }}
      uses: actions/upload-artifact@v4
      with:
        name: linknode-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
        
    - name: Build Summary
      run: |
        echo "### 🚀 Build Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Version Code:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "**Build Type:** ${{ github.event.inputs.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📦 **Download artifacts below and upload to Google Play Console**" >> $GITHUB_STEP_SUMMARY